server:
  port: 8001

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/email-sending
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
